---
--- Created by inb.
--- DateTime: 01/06/2023 09:19
---
function update_add_ui_interaction() end
function update_add_ui_interaction_special() end
function update_animations() end
function update_boot_override() end
function update_camera_local_rotate_inv() end
function update_chat() end
function update_create_workshop_mod() end
function update_cursor_state() end
function update_damage_zones() end
function update_exit_pause_menu() end
function update_get_active_input_type() end
function update_get_angle_2d() end
function update_get_application_state() end
function update_get_attachment_ammo_item_type() end
function update_get_attachment_option() end
function update_get_attachment_option_count() end
function update_get_attachment_option_hidden() end
function update_get_camera_forward() end
function update_get_camera_fov() end
function update_get_camera_heading() end
function update_get_camera_position() end
function update_get_camera_side() end
function update_get_chat_messages() end
function update_get_connect_address() end
function update_get_currency_log() end
function update_get_currency_log_count() end
function update_get_definition_vehicle_stats() end
function update_get_delivery_log() end
function update_get_delivery_log_count() end
function update_get_friend_games() end
function update_get_game_input_category() end
function update_get_game_input_count() end
function update_get_game_input_name() end
function update_get_game_settings() end
function update_get_gfx_resolution_modes() end
function update_get_hair_color_options() end
function update_get_host_connect_token() end
function update_get_host_max_players() end
function update_get_host_password() end
function update_get_input_binding_gamepad_axis() end
function update_get_input_binding_gamepad_button() end
function update_get_input_binding_is_axis_inverted() end
function update_get_input_binding_joystick_axis() end
function update_get_input_binding_joystick_button() end
function update_get_input_binding_joystick_connected() end
function update_get_input_binding_joystick_guid() end
function update_get_input_binding_joystick_name() end
function update_get_input_binding_keyboard_key() end
function update_get_input_binding_keyboard_pointer() end
function update_get_input_category_name() end
function update_get_input_gamepad_axis_value() end
function update_get_input_joystick_axis_count() end
function update_get_input_joystick_axis_value() end
function update_get_input_joystick_connected() end
function update_get_input_joystick_guid() end
function update_get_input_joystick_name() end
function update_get_is_focus_local() end
function update_get_is_hosting_game() end
function update_get_is_input_rebindable_gamepad() end
function update_get_is_input_rebindable_gamepad_as_axis() end
function update_get_is_input_rebindable_keyboard() end
function update_get_is_loading() end
function update_get_is_multiplayer() end
function update_get_is_notification_holomap_set() end
function update_get_is_respawn_menu_option_available() end
function update_get_is_save_game_available() end
function update_get_is_show_controls() end
function update_get_is_show_subtitles() end
function update_get_is_show_tooltips() end
function update_get_is_show_voice_chat_others() end
function update_get_is_show_voice_chat_self() end
function update_get_is_show_vr_multiplayer_warning() end
function update_get_is_vr() end
function update_get_join_password() end
function update_get_key_name() end
function update_get_keyboard_back_opens_pause() end
function update_get_loc() end
function update_get_local_peer_id() end
function update_get_local_team_id() end
function update_get_logic_tick() end
function update_get_map_destroyed_vehicle() end
function update_get_map_destroyed_vehicle_count() end
function update_get_map_vehicle_by_id() end
function update_get_map_vehicle_by_index() end
function update_get_map_vehicle_count() end
function update_get_map_vehicle_position_relate_to_parent_vehicle() end
function update_get_message_box_type() end
function update_get_missile_by_id() end
function update_get_missile_by_index() end
function update_get_missile_count() end
function update_get_mod_details() end
function update_get_mod_incompatible_active_mods() end
function update_get_mod_workshop_upload_status() end
function update_get_mouse_flight_axis() end
function update_get_mouse_flight_mode() end
function update_get_network_time_since_recv() end
function update_get_network_timeout() end
function update_get_new_game_base_difficulty() end
function update_get_new_game_blueprints() end
function update_get_new_game_carrier_count_per_team() end
function update_get_new_game_is_tutorial() end
function update_get_new_game_island_count() end
function update_get_new_game_island_count_per_team() end
function update_get_new_game_loadout_type() end
function update_get_new_game_team_count_ai() end
function update_get_new_game_team_count_human() end
function update_get_notification_holomap() end
function update_get_notification_log() end
function update_get_notification_log_count() end
function update_get_ocean_current_velocity() end
function update_get_ocean_depth_factor() end
function update_get_peer_count() end
function update_get_peer_id() end
function update_get_peer_index_by_id() end
function update_get_peer_is_admin() end
function update_get_peer_is_voice_muted() end
function update_get_peer_is_voice_transmit() end
function update_get_peer_name() end
function update_get_peer_team() end
function update_get_rebinding_gamepad() end
function update_get_rebinding_keyboard() end
function update_get_render_buffer_age() end
function update_get_resource_inventory_category_count() end
function update_get_resource_inventory_category_data() end
function update_get_resource_inventory_item_count() end
function update_get_resource_inventory_item_data() end
function update_get_resource_item_for_definition() end
function update_get_resource_item_hidden() end
function update_get_resource_item_hidden_facility_production() end
function update_get_respawn_carrier_id() end
function update_get_save_slots() end
function update_get_screen_input() end
function update_get_screen_state_active() end
function update_get_screen_team_id() end
function update_get_screen_vehicle() end
function update_get_server_list() end
function update_get_server_meta() end
function update_get_server_name() end
function update_get_skin_color_options() end
function update_get_team() end
function update_get_team_color() end
function update_get_team_transmission_count() end
function update_get_team_transmission_name() end
function update_get_tile_by_id() end
function update_get_tile_by_index() end
function update_get_tile_count() end
function update_get_time_ms() end
function update_get_time_since_epoch() end
function update_get_transmission_playback_progress() end
function update_get_transmission_playing_index() end
function update_get_ui_scale() end
function update_get_vehicle_by_id() end
function update_get_version() end
function update_get_weapon_line_by_index() end
function update_get_weapon_line_count() end
function update_get_weather_fog_factor() end
function update_get_weather_lightning_factor() end
function update_get_weather_precipitation_factor() end
function update_get_weather_wind_velocity() end
function update_get_workshop_published_mods() end
function update_gun_funnel() end
function update_interaction_ui() end
function update_launch_carrier() end
function update_map_cursor_state() end
function update_map_dismiss_notification() end
function update_map_hovered() end
function update_play_sound() end
function update_play_transmission() end
function update_print_metatable() end
function update_print_regions() end
function update_refresh_workshop_published_mods() end
function update_repeat() end
function update_screen_overrides() end
function update_self_destruct_override() end
function update_set_connect_address() end
function update_set_go_code() end
function update_set_host_max_players() end
function update_set_host_password() end
function update_set_is_block_input() end
function update_set_is_mod_enabled() end
function update_set_is_pause_simulation() end
function update_set_is_text_input_mode() end
function update_set_is_visible() end
function update_set_join_password() end
function update_set_new_game_base_difficulty() end
function update_set_new_game_blueprints() end
function update_set_new_game_carrier_count_per_team() end
function update_set_new_game_is_tutorial() end
function update_set_new_game_island_count() end
function update_set_new_game_island_count_per_team() end
function update_set_new_game_loadout_type() end
function update_set_new_game_team_count_ai() end
function update_set_new_game_team_count_human() end
function update_set_observed_vehicle() end
function update_set_screen_background_clip() end
function update_set_screen_background_color() end
function update_set_screen_background_is_render_islands() end
function update_set_screen_background_tile_color_custom() end
function update_set_screen_background_type() end
function update_set_screen_camera_attach_vehicle() end
function update_set_screen_camera_cull_distance() end
function update_set_screen_camera_is_render_ocean() end
function update_set_screen_camera_lod_level() end
function update_set_screen_camera_pos_orientation() end
function update_set_screen_camera_render_attached_vehicle() end
function update_set_screen_map_position_scale() end
function update_set_screen_state_exit() end
function update_set_screen_vehicle_control_id() end
function update_set_server_name() end
function update_stop_transmission() end
function update_string_from_epoch() end
function update_ui_add_triangle() end
function update_ui_begin_triangles() end
function update_ui_circle() end
function update_ui_end_triangles() end
function update_ui_event() end
function update_ui_format_peer_display_name() end
function update_ui_get_image_size() end
function update_ui_get_offset() end
function update_ui_get_text_size() end
function update_ui_image() end
function update_ui_image_power() end
function update_ui_image_rot() end
function update_ui_line() end
function update_ui_pop_alpha() end
function update_ui_pop_clip() end
function update_ui_pop_offset() end
function update_ui_pop_scale() end
function update_ui_push_alpha() end
function update_ui_push_clip() end
function update_ui_push_offset() end
function update_ui_push_scale() end
function update_ui_rectangle() end
function update_ui_rectangle_outline() end
function update_ui_set_back_color() end
function update_ui_set_text_color() end
function update_ui_text() end
function update_ui_text_scale() end
function update_update_workshop_mod() end
function update_world_to_screen() end